package html

// DO NOT EDIT
// This file was generated using github.com/macabot/hypp/driver/html/cmd/generate-tags

import "github.com/macabot/hypp"

var hierarchy = map[string]string{
	"meta":                    "HTMLMetaElement",
	"output":                  "HTMLOutputElement",
	"HTMLScriptElement":       "HTMLElement",
	"hatch":                   "HTMLUnknownElement",
	"summary":                 "HTMLElement",
	"feOffset":                "HTMLUnknownElement",
	"aside":                   "HTMLElement",
	"data":                    "HTMLDataElement",
	"h5":                      "HTMLHeadingElement",
	"HTMLLinkElement":         "HTMLElement",
	"header":                  "HTMLElement",
	"HTMLTitleElement":        "HTMLElement",
	"feMergeNode":             "HTMLUnknownElement",
	"mpath":                   "HTMLUnknownElement",
	"HTMLHtmlElement":         "HTMLElement",
	"animateTransform":        "HTMLUnknownElement",
	"feFlood":                 "HTMLUnknownElement",
	"textPath":                "HTMLUnknownElement",
	"dd":                      "HTMLElement",
	"small":                   "HTMLElement",
	"meshgradient":            "HTMLUnknownElement",
	"HTMLAreaElement":         "HTMLElement",
	"HTMLQuoteElement":        "HTMLElement",
	"em":                      "HTMLElement",
	"HTMLIFrameElement":       "HTMLElement",
	"HTMLMediaElement":        "HTMLElement",
	"option":                  "HTMLOptionElement",
	"feConvolveMatrix":        "HTMLUnknownElement",
	"linearGradient":          "HTMLUnknownElement",
	"hr":                      "HTMLHRElement",
	"ruby":                    "HTMLElement",
	"HTMLMetaElement":         "HTMLElement",
	"sup":                     "HTMLElement",
	"video":                   "HTMLVideoElement",
	"path":                    "HTMLUnknownElement",
	"cite":                    "HTMLElement",
	"dfn":                     "HTMLElement",
	"HTMLLabelElement":        "HTMLElement",
	"script":                  "HTMLScriptElement",
	"fePointLight":            "HTMLUnknownElement",
	"filter":                  "HTMLUnknownElement",
	"line":                    "HTMLUnknownElement",
	"feColorMatrix":           "HTMLUnknownElement",
	"mesh":                    "HTMLUnknownElement",
	"HTMLHeadElement":         "HTMLElement",
	"portal":                  "HTMLUnknownElement",
	"HTMLSelectElement":       "HTMLElement",
	"table":                   "HTMLTableElement",
	"q":                       "HTMLQuoteElement",
	"set":                     "HTMLUnknownElement",
	"canvas":                  "HTMLCanvasElement",
	"HTMLTableCellElement":    "HTMLElement",
	"feComposite":             "HTMLUnknownElement",
	"feGaussianBlur":          "HTMLUnknownElement",
	"a":                       "HTMLAnchorElement",
	"ul":                      "HTMLUListElement",
	"marker":                  "HTMLUnknownElement",
	"HTMLOutputElement":       "HTMLElement",
	"HTMLStyleElement":        "HTMLElement",
	"feSpecularLighting":      "HTMLUnknownElement",
	"g":                       "HTMLUnknownElement",
	"button":                  "HTMLButtonElement",
	"HTMLDataElement":         "HTMLElement",
	"dt":                      "HTMLElement",
	"HTMLObjectElement":       "HTMLElement",
	"HTMLSlotElement":         "HTMLElement",
	"ellipse":                 "HTMLUnknownElement",
	"HTMLElement":             "Element",
	"article":                 "HTMLElement",
	"feImage":                 "HTMLUnknownElement",
	"radialGradient":          "HTMLUnknownElement",
	"hatchpath":               "HTMLUnknownElement",
	"use":                     "HTMLUnknownElement",
	"bdi":                     "HTMLElement",
	"br":                      "HTMLBRElement",
	"HTMLDListElement":        "HTMLElement",
	"HTMLUListElement":        "HTMLElement",
	"p":                       "HTMLParagraphElement",
	"defs":                    "HTMLUnknownElement",
	"input":                   "HTMLInputElement",
	"feFuncG":                 "HTMLUnknownElement",
	"figcaption":              "HTMLElement",
	"image":                   "HTMLElement",
	"HTMLTextAreaElement":     "HTMLElement",
	"body":                    "HTMLBodyElement",
	"HTMLDivElement":          "HTMLElement",
	"label":                   "HTMLLabelElement",
	"progress":                "HTMLProgressElement",
	"HTMLSpanElement":         "HTMLElement",
	"address":                 "HTMLElement",
	"details":                 "HTMLDetailsElement",
	"dl":                      "HTMLDListElement",
	"span":                    "HTMLSpanElement",
	"pre":                     "HTMLPreElement",
	"feComponentTransfer":     "HTMLUnknownElement",
	"foreignObject":           "HTMLUnknownElement",
	"caption":                 "HTMLTableCaptionElement",
	"HTMLLegendElement":       "HTMLElement",
	"li":                      "HTMLLIElement",
	"picture":                 "HTMLPictureElement",
	"HTMLTableRowElement":     "HTMLElement",
	"audio":                   "HTMLAudioElement",
	"HTMLButtonElement":       "HTMLElement",
	"h3":                      "HTMLHeadingElement",
	"meter":                   "HTMLMeterElement",
	"tbody":                   "HTMLTableSectionElement",
	"tfoot":                   "HTMLTableSectionElement",
	"HTMLVideoElement":        "HTMLMediaElement",
	"EventTarget":             "Object",
	"img":                     "HTMLImageElement",
	"feMorphology":            "HTMLUnknownElement",
	"var":                     "HTMLElement",
	"bdo":                     "HTMLElement",
	"code":                    "HTMLElement",
	"head":                    "HTMLHeadElement",
	"s":                       "HTMLElement",
	"main":                    "HTMLElement",
	"samp":                    "HTMLElement",
	"wbr":                     "HTMLElement",
	"embed":                   "HTMLEmbedElement",
	"HTMLBodyElement":         "HTMLElement",
	"h2":                      "HTMLHeadingElement",
	"feFuncA":                 "HTMLUnknownElement",
	"ol":                      "HTMLOListElement",
	"td":                      "HTMLTableCellElement",
	"pattern":                 "HTMLUnknownElement",
	"b":                       "HTMLElement",
	"kbd":                     "HTMLElement",
	"map":                     "HTMLMapElement",
	"animateMotion":           "HTMLUnknownElement",
	"slot":                    "HTMLSlotElement",
	"HTMLTimeElement":         "HTMLElement",
	"discard":                 "HTMLUnknownElement",
	"HTMLCanvasElement":       "HTMLElement",
	"colgroup":                "HTMLTableColElement",
	"HTMLFieldSetElement":     "HTMLElement",
	"HTMLLIElement":           "HTMLElement",
	"nav":                     "HTMLElement",
	"feTile":                  "HTMLUnknownElement",
	"HTMLBaseElement":         "HTMLElement",
	"HTMLDetailsElement":      "HTMLElement",
	"HTMLImageElement":        "HTMLElement",
	"clipPath":                "HTMLUnknownElement",
	"feDistantLight":          "HTMLUnknownElement",
	"HTMLDataListElement":     "HTMLElement",
	"link":                    "HTMLLinkElement",
	"select":                  "HTMLSelectElement",
	"desc":                    "HTMLUnknownElement",
	"template":                "HTMLTemplateElement",
	"textarea":                "HTMLTextAreaElement",
	"area":                    "HTMLAreaElement",
	"figure":                  "HTMLElement",
	"html":                    "HTMLHtmlElement",
	"HTMLTableElement":        "HTMLElement",
	"h6":                      "HTMLHeadingElement",
	"noscript":                "HTMLElement",
	"HTMLOptionElement":       "HTMLElement",
	"datalist":                "HTMLDataListElement",
	"rp":                      "HTMLElement",
	"feBlend":                 "HTMLUnknownElement",
	"tspan":                   "HTMLUnknownElement",
	"polyline":                "HTMLUnknownElement",
	"form":                    "HTMLFormElement",
	"h4":                      "HTMLHeadingElement",
	"mark":                    "HTMLElement",
	"section":                 "HTMLElement",
	"HTMLInputElement":        "HTMLElement",
	"HTMLParamElement":        "HTMLElement",
	"abbr":                    "HTMLElement",
	"HTMLAudioElement":        "HTMLMediaElement",
	"blockquote":              "HTMLQuoteElement",
	"HTMLUnknownElement":      "HTMLElement",
	"del":                     "HTMLModElement",
	"tr":                      "HTMLTableRowElement",
	"meshrow":                 "HTMLUnknownElement",
	"view":                    "HTMLUnknownElement",
	"HTMLAnchorElement":       "HTMLElement",
	"HTMLTableCaptionElement": "HTMLElement",
	"th":                      "HTMLTableCellElement",
	"HTMLMeterElement":        "HTMLElement",
	"HTMLParagraphElement":    "HTMLElement",
	"HTMLTableSectionElement": "HTMLElement",
	"Element":                 "Node",
	"HTMLModElement":          "HTMLElement",
	"dialog":                  "HTMLUnknownElement",
	"menu":                    "HTMLMenuElement",
	"circle":                  "HTMLUnknownElement",
	"feDisplacementMap":       "HTMLUnknownElement",
	"i":                       "HTMLElement",
	"ins":                     "HTMLModElement",
	"param":                   "HTMLParamElement",
	"rt":                      "HTMLElement",
	"feDiffuseLighting":       "HTMLUnknownElement",
	"div":                     "HTMLDivElement",
	"footer":                  "HTMLElement",
	"HTMLMapElement":          "HTMLElement",
	"HTMLTemplateElement":     "HTMLElement",
	"HTMLEmbedElement":        "HTMLElement",
	"math":                    "HTMLUnknownElement",
	"HTMLOListElement":        "HTMLElement",
	"thead":                   "HTMLTableSectionElement",
	"feMerge":                 "HTMLUnknownElement",
	"switch":                  "HTMLUnknownElement",
	"HTMLMenuElement":         "HTMLElement",
	"u":                       "HTMLElement",
	"feFuncR":                 "HTMLUnknownElement",
	"rect":                    "HTMLUnknownElement",
	"feTurbulence":            "HTMLUnknownElement",
	"HTMLBRElement":           "HTMLElement",
	"HTMLTableColElement":     "HTMLElement",
	"style":                   "HTMLStyleElement",
	"sub":                     "HTMLElement",
	"h1":                      "HTMLHeadingElement",
	"optgroup":                "HTMLOptGroupElement",
	"HTMLSourceElement":       "HTMLElement",
	"text":                    "HTMLUnknownElement",
	"HTMLFormElement":         "HTMLElement",
	"HTMLPreElement":          "HTMLElement",
	"title":                   "HTMLTitleElement",
	"metadata":                "HTMLUnknownElement",
	"object":                  "HTMLObjectElement",
	"track":                   "HTMLTrackElement",
	"HTMLTrackElement":        "HTMLElement",
	"base":                    "HTMLBaseElement",
	"col":                     "HTMLTableColElement",
	"fieldset":                "HTMLFieldSetElement",
	"HTMLHRElement":           "HTMLElement",
	"HTMLHeadingElement":      "HTMLElement",
	"feFuncB":                 "HTMLUnknownElement",
	"mask":                    "HTMLUnknownElement",
	"meshpatch":               "HTMLUnknownElement",
	"symbol":                  "HTMLUnknownElement",
	"Node":                    "EventTarget",
	"HTMLProgressElement":     "HTMLElement",
	"strong":                  "HTMLElement",
	"feDropShadow":            "HTMLUnknownElement",
	"HTMLPictureElement":      "HTMLElement",
	"source":                  "HTMLSourceElement",
	"animate":                 "HTMLUnknownElement",
	"time":                    "HTMLTimeElement",
	"feSpotLight":             "HTMLUnknownElement",
	"polygon":                 "HTMLUnknownElement",
	"stop":                    "HTMLUnknownElement",
	"iframe":                  "HTMLIFrameElement",
	"legend":                  "HTMLLegendElement",
	"HTMLOptGroupElement":     "HTMLElement",
	"svg":                     "HTMLUnknownElement",
}

var ownProps = map[string]hypp.Set[string]{
	"HTMLVideoElement":        hypp.NewSet("getVideoPlaybackQuality", "width", "height", "videoWidth", "videoHeight", "poster", "mozParsedFrames", "mozDecodedFrames", "mozPresentedFrames", "mozPaintedFrames", "mozFrameDelay", "mozHasAudio", "constructor"),
	"HTMLLabelElement":        hypp.NewSet("form", "htmlFor", "control", "constructor"),
	"HTMLOutputElement":       hypp.NewSet("checkValidity", "reportValidity", "setCustomValidity", "htmlFor", "form", "name", "type", "defaultValue", "value", "willValidate", "validity", "validationMessage", "labels", "constructor"),
	"HTMLSelectElement":       hypp.NewSet("item", "namedItem", "add", "remove", "checkValidity", "reportValidity", "setCustomValidity", "autofocus", "autocomplete", "disabled", "form", "multiple", "name", "required", "size", "type", "options", "length", "selectedOptions", "selectedIndex", "value", "willValidate", "validity", "validationMessage", "labels", "constructor"),
	"HTMLBodyElement":         hypp.NewSet("text", "link", "vLink", "aLink", "bgColor", "background", "onafterprint", "onbeforeprint", "onbeforeunload", "onhashchange", "onlanguagechange", "onmessage", "onmessageerror", "onoffline", "ononline", "onpagehide", "onpageshow", "onpopstate", "onrejectionhandled", "onstorage", "onunhandledrejection", "onunload", "ongamepadconnected", "ongamepaddisconnected", "constructor"),
	"HTMLModElement":          hypp.NewSet("cite", "dateTime", "constructor"),
	"HTMLSlotElement":         hypp.NewSet("assignedNodes", "assignedElements", "assign", "name", "constructor"),
	"HTMLAreaElement":         hypp.NewSet("toString", "alt", "coords", "shape", "target", "download", "ping", "rel", "referrerPolicy", "relList", "noHref", "href", "origin", "protocol", "username", "password", "host", "hostname", "port", "pathname", "search", "hash", "constructor"),
	"HTMLUnknownElement":      hypp.NewSet("constructor"),
	"HTMLParamElement":        hypp.NewSet("name", "value", "type", "valueType", "constructor"),
	"HTMLLinkElement":         hypp.NewSet("disabled", "href", "crossOrigin", "rel", "relList", "media", "hreflang", "type", "referrerPolicy", "sizes", "imageSrcset", "imageSizes", "charset", "rev", "target", "integrity", "as", "sheet", "constructor"),
	"HTMLMapElement":          hypp.NewSet("name", "areas", "constructor"),
	"HTMLMetaElement":         hypp.NewSet("name", "httpEquiv", "content", "scheme", "constructor"),
	"HTMLOListElement":        hypp.NewSet("reversed", "start", "type", "compact", "constructor"),
	"Element":                 hypp.NewSet("getAttributeNames", "getAttribute", "getAttributeNS", "toggleAttribute", "setAttribute", "setAttributeNS", "removeAttribute", "removeAttributeNS", "hasAttribute", "hasAttributeNS", "hasAttributes", "closest", "matches", "webkitMatchesSelector", "getElementsByTagName", "getElementsByTagNameNS", "getElementsByClassName", "insertAdjacentElement", "insertAdjacentText", "mozMatchesSelector", "setPointerCapture", "releasePointerCapture", "hasPointerCapture", "setCapture", "releaseCapture", "getAttributeNode", "setAttributeNode", "removeAttributeNode", "getAttributeNodeNS", "setAttributeNodeNS", "getClientRects", "getBoundingClientRect", "scrollIntoView", "scroll", "scrollTo", "scrollBy", "insertAdjacentHTML", "querySelector", "querySelectorAll", "attachShadow", "requestFullscreen", "mozRequestFullScreen", "requestPointerLock", "animate", "getAnimations", "before", "after", "replaceWith", "remove", "prepend", "append", "replaceChildren", "namespaceURI", "prefix", "localName", "tagName", "id", "className", "classList", "part", "attributes", "scrollTop", "scrollLeft", "scrollWidth", "scrollHeight", "clientTop", "clientLeft", "clientWidth", "clientHeight", "scrollTopMax", "scrollLeftMax", "innerHTML", "outerHTML", "shadowRoot", "assignedSlot", "slot", "onfullscreenchange", "onfullscreenerror", "previousElementSibling", "nextElementSibling", "children", "firstElementChild", "lastElementChild", "childElementCount", "constructor"),
	"EventTarget":             hypp.NewSet("addEventListener", "removeEventListener", "dispatchEvent", "constructor"),
	"HTMLCanvasElement":       hypp.NewSet("getContext", "toDataURL", "toBlob", "captureStream", "width", "height", "mozOpaque", "mozPrintCallback", "constructor"),
	"HTMLStyleElement":        hypp.NewSet("disabled", "media", "type", "sheet", "constructor"),
	"HTMLUListElement":        hypp.NewSet("compact", "type", "constructor"),
	"HTMLDataListElement":     hypp.NewSet("options", "constructor"),
	"HTMLImageElement":        hypp.NewSet("decode", "alt", "src", "srcset", "crossOrigin", "useMap", "referrerPolicy", "isMap", "width", "height", "decoding", "loading", "naturalWidth", "naturalHeight", "complete", "name", "align", "hspace", "vspace", "longDesc", "border", "sizes", "currentSrc", "lowsrc", "x", "y", "constructor"),
	"HTMLLegendElement":       hypp.NewSet("form", "align", "constructor"),
	"HTMLProgressElement":     hypp.NewSet("value", "max", "position", "labels", "constructor"),
	"HTMLDListElement":        hypp.NewSet("compact", "constructor"),
	"HTMLHeadElement":         hypp.NewSet("constructor"),
	"HTMLOptionElement":       hypp.NewSet("disabled", "form", "label", "defaultSelected", "selected", "value", "text", "index", "constructor"),
	"HTMLHRElement":           hypp.NewSet("align", "color", "noShade", "size", "width", "constructor"),
	"Object":                  hypp.NewSet("toString", "toLocaleString", "valueOf", "hasOwnProperty", "isPrototypeOf", "propertyIsEnumerable", "__defineGetter__", "__defineSetter__", "__lookupGetter__", "__lookupSetter__", "__proto__", "constructor"),
	"HTMLAudioElement":        hypp.NewSet("constructor"),
	"HTMLDataElement":         hypp.NewSet("value", "constructor"),
	"HTMLInputElement":        hypp.NewSet("stepUp", "stepDown", "checkValidity", "reportValidity", "setCustomValidity", "select", "setRangeText", "setSelectionRange", "mozIsTextField", "accept", "alt", "autocomplete", "autofocus", "defaultChecked", "checked", "disabled", "form", "files", "formAction", "formEnctype", "formMethod", "formNoValidate", "formTarget", "height", "indeterminate", "list", "max", "maxLength", "min", "minLength", "multiple", "name", "pattern", "placeholder", "readOnly", "required", "size", "src", "step", "type", "defaultValue", "value", "valueAsDate", "valueAsNumber", "width", "willValidate", "validity", "validationMessage", "labels", "selectionStart", "selectionEnd", "selectionDirection", "align", "useMap", "textLength", "webkitEntries", "webkitdirectory", "constructor"),
	"HTMLBRElement":           hypp.NewSet("clear", "constructor"),
	"HTMLTableCaptionElement": hypp.NewSet("align", "constructor"),
	"HTMLHtmlElement":         hypp.NewSet("version", "constructor"),
	"HTMLIFrameElement":       hypp.NewSet("getSVGDocument", "src", "srcdoc", "name", "sandbox", "allowFullscreen", "width", "height", "referrerPolicy", "contentDocument", "contentWindow", "align", "scrolling", "frameBorder", "longDesc", "marginHeight", "marginWidth", "allow", "constructor"),
	"HTMLAnchorElement":       hypp.NewSet("toString", "target", "download", "ping", "rel", "referrerPolicy", "relList", "hreflang", "type", "text", "coords", "charset", "name", "rev", "shape", "href", "origin", "protocol", "username", "password", "host", "hostname", "port", "pathname", "search", "hash", "constructor"),
	"HTMLElement":             hypp.NewSet("click", "attachInternals", "focus", "blur", "title", "lang", "dir", "innerText", "hidden", "accessKey", "accessKeyLabel", "draggable", "contentEditable", "isContentEditable", "spellcheck", "inputMode", "enterKeyHint", "nonce", "offsetParent", "offsetTop", "offsetLeft", "offsetWidth", "offsetHeight", "oncopy", "oncut", "onpaste", "style", "onabort", "onblur", "onfocus", "onauxclick", "onbeforeinput", "oncanplay", "oncanplaythrough", "onchange", "onclick", "onclose", "oncontextmenu", "oncuechange", "ondblclick", "ondrag", "ondragend", "ondragenter", "ondragexit", "ondragleave", "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied", "onended", "onformdata", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup", "onload", "onloadeddata", "onloadedmetadata", "onloadend", "onloadstart", "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onwheel", "onpause", "onplay", "onplaying", "onprogress", "onratechange", "onreset", "onresize", "onscroll", "onsecuritypolicyviolation", "onseeked", "onseeking", "onselect", "onslotchange", "onstalled", "onsubmit", "onsuspend", "ontimeupdate", "onvolumechange", "onwaiting", "onselectstart", "onselectionchange", "ontoggle", "onpointercancel", "onpointerdown", "onpointerup", "onpointermove", "onpointerout", "onpointerover", "onpointerenter", "onpointerleave", "ongotpointercapture", "onlostpointercapture", "onmozfullscreenchange", "onmozfullscreenerror", "onanimationcancel", "onanimationend", "onanimationiteration", "onanimationstart", "ontransitioncancel", "ontransitionend", "ontransitionrun", "ontransitionstart", "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart", "onwebkittransitionend", "dataset", "tabIndex", "onerror", "constructor"),
	"HTMLMediaElement":        hypp.NewSet("load", "canPlayType", "fastSeek", "play", "pause", "addTextTrack", "mozCaptureStream", "mozCaptureStreamUntilEnded", "mozGetMetadata", "setMediaKeys", "seekToNextFrame", "error", "src", "currentSrc", "crossOrigin", "networkState", "preload", "buffered", "readyState", "seeking", "currentTime", "duration", "paused", "defaultPlaybackRate", "playbackRate", "played", "seekable", "ended", "autoplay", "loop", "controls", "volume", "muted", "defaultMuted", "textTracks", "srcObject", "mozPreservesPitch", "mozAudioCaptured", "mozFragmentEnd", "mediaKeys", "onencrypted", "onwaitingforkey", "NETWORK_EMPTY", "NETWORK_IDLE", "NETWORK_LOADING", "NETWORK_NO_SOURCE", "HAVE_NOTHING", "HAVE_METADATA", "HAVE_CURRENT_DATA", "HAVE_FUTURE_DATA", "HAVE_ENOUGH_DATA", "constructor"),
	"HTMLScriptElement":       hypp.NewSet("src", "type", "noModule", "charset", "async", "defer", "crossOrigin", "referrerPolicy", "text", "event", "htmlFor", "integrity", "constructor"),
	"HTMLTrackElement":        hypp.NewSet("kind", "src", "srclang", "label", "default", "readyState", "track", "NONE", "LOADING", "LOADED", "ERROR", "constructor"),
	"HTMLEmbedElement":        hypp.NewSet("getSVGDocument", "src", "type", "width", "height", "align", "name", "constructor"),
	"HTMLFieldSetElement":     hypp.NewSet("checkValidity", "reportValidity", "setCustomValidity", "disabled", "form", "name", "type", "elements", "willValidate", "validity", "validationMessage", "constructor"),
	"HTMLLIElement":           hypp.NewSet("value", "type", "constructor"),
	"HTMLButtonElement":       hypp.NewSet("checkValidity", "reportValidity", "setCustomValidity", "autofocus", "disabled", "form", "formAction", "formEnctype", "formMethod", "formNoValidate", "formTarget", "name", "type", "value", "willValidate", "validity", "validationMessage", "labels", "constructor"),
	"HTMLDetailsElement":      hypp.NewSet("open", "constructor"),
	"HTMLTableSectionElement": hypp.NewSet("insertRow", "deleteRow", "rows", "align", "ch", "chOff", "vAlign", "constructor"),
	"HTMLTitleElement":        hypp.NewSet("text", "constructor"),
	"HTMLTableRowElement":     hypp.NewSet("insertCell", "deleteCell", "rowIndex", "sectionRowIndex", "cells", "align", "ch", "chOff", "vAlign", "bgColor", "constructor"),
	"Node":                    hypp.NewSet("getRootNode", "hasChildNodes", "insertBefore", "appendChild", "replaceChild", "removeChild", "normalize", "cloneNode", "isSameNode", "isEqualNode", "compareDocumentPosition", "contains", "lookupPrefix", "lookupNamespaceURI", "isDefaultNamespace", "nodeType", "nodeName", "baseURI", "isConnected", "ownerDocument", "parentNode", "parentElement", "childNodes", "firstChild", "lastChild", "previousSibling", "nextSibling", "nodeValue", "textContent", "ELEMENT_NODE", "ATTRIBUTE_NODE", "TEXT_NODE", "CDATA_SECTION_NODE", "ENTITY_REFERENCE_NODE", "ENTITY_NODE", "PROCESSING_INSTRUCTION_NODE", "COMMENT_NODE", "DOCUMENT_NODE", "DOCUMENT_TYPE_NODE", "DOCUMENT_FRAGMENT_NODE", "NOTATION_NODE", "DOCUMENT_POSITION_DISCONNECTED", "DOCUMENT_POSITION_PRECEDING", "DOCUMENT_POSITION_FOLLOWING", "DOCUMENT_POSITION_CONTAINS", "DOCUMENT_POSITION_CONTAINED_BY", "DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC", "constructor"),
	"HTMLBaseElement":         hypp.NewSet("href", "target", "constructor"),
	"HTMLQuoteElement":        hypp.NewSet("cite", "constructor"),
	"HTMLPictureElement":      hypp.NewSet("constructor"),
	"HTMLSpanElement":         hypp.NewSet("constructor"),
	"HTMLTableElement":        hypp.NewSet("createCaption", "deleteCaption", "createTHead", "deleteTHead", "createTFoot", "deleteTFoot", "createTBody", "insertRow", "deleteRow", "caption", "tHead", "tFoot", "tBodies", "rows", "align", "border", "frame", "rules", "summary", "width", "bgColor", "cellPadding", "cellSpacing", "constructor"),
	"HTMLTemplateElement":     hypp.NewSet("content", "constructor"),
	"HTMLTimeElement":         hypp.NewSet("dateTime", "constructor"),
	"HTMLTableColElement":     hypp.NewSet("span", "align", "ch", "chOff", "vAlign", "width", "constructor"),
	"HTMLHeadingElement":      hypp.NewSet("align", "constructor"),
	"HTMLParagraphElement":    hypp.NewSet("align", "constructor"),
	"HTMLTableCellElement":    hypp.NewSet("colSpan", "rowSpan", "headers", "cellIndex", "abbr", "scope", "align", "axis", "height", "width", "ch", "chOff", "noWrap", "vAlign", "bgColor", "constructor"),
	"HTMLTextAreaElement":     hypp.NewSet("checkValidity", "reportValidity", "setCustomValidity", "select", "setRangeText", "setSelectionRange", "autocomplete", "autofocus", "cols", "disabled", "form", "maxLength", "minLength", "name", "placeholder", "readOnly", "required", "rows", "wrap", "type", "defaultValue", "value", "textLength", "willValidate", "validity", "validationMessage", "labels", "selectionStart", "selectionEnd", "selectionDirection", "constructor"),
	"HTMLDivElement":          hypp.NewSet("align", "constructor"),
	"HTMLObjectElement":       hypp.NewSet("checkValidity", "reportValidity", "setCustomValidity", "getSVGDocument", "data", "type", "name", "useMap", "form", "width", "height", "contentDocument", "contentWindow", "willValidate", "validity", "validationMessage", "align", "archive", "code", "declare", "hspace", "standby", "vspace", "codeBase", "codeType", "border", "constructor"),
	"HTMLSourceElement":       hypp.NewSet("src", "type", "srcset", "sizes", "media", "constructor"),
	"HTMLFormElement":         hypp.NewSet("submit", "requestSubmit", "reset", "checkValidity", "reportValidity", "acceptCharset", "action", "autocomplete", "enctype", "encoding", "method", "name", "noValidate", "target", "elements", "length", "constructor"),
	"HTMLPreElement":          hypp.NewSet("width", "constructor"),
	"HTMLMenuElement":         hypp.NewSet("compact", "constructor"),
	"HTMLMeterElement":        hypp.NewSet("value", "min", "max", "low", "high", "optimum", "labels", "constructor"),
	"HTMLOptGroupElement":     hypp.NewSet("disabled", "label", "constructor"),
}
