// Code generated by mockery v2.43.0. DO NOT EDIT.

package js

import (
	js "github.com/macabot/hypp/js"
	mock "github.com/stretchr/testify/mock"
)

// MockValueDriver is an autogenerated mock type for the ValueDriver type
type MockValueDriver struct {
	mock.Mock
}

type MockValueDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValueDriver) EXPECT() *MockValueDriver_Expecter {
	return &MockValueDriver_Expecter{mock: &_m.Mock}
}

// Bool provides a mock function with given fields:
func (_m *MockValueDriver) Bool() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bool")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_Bool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bool'
type MockValueDriver_Bool_Call struct {
	*mock.Call
}

// Bool is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) Bool() *MockValueDriver_Bool_Call {
	return &MockValueDriver_Bool_Call{Call: _e.mock.On("Bool")}
}

func (_c *MockValueDriver_Bool_Call) Run(run func()) *MockValueDriver_Bool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_Bool_Call) Return(_a0 bool) *MockValueDriver_Bool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Bool_Call) RunAndReturn(run func() bool) *MockValueDriver_Bool_Call {
	_c.Call.Return(run)
	return _c
}

// Call provides a mock function with given fields: m, args
func (_m *MockValueDriver) Call(m string, args ...interface{}) js.Value {
	var _ca []interface{}
	_ca = append(_ca, m)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func(string, ...interface{}) js.Value); ok {
		r0 = rf(m, args...)
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockValueDriver_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockValueDriver_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - m string
//   - args ...interface{}
func (_e *MockValueDriver_Expecter) Call(m interface{}, args ...interface{}) *MockValueDriver_Call_Call {
	return &MockValueDriver_Call_Call{Call: _e.mock.On("Call",
		append([]interface{}{m}, args...)...)}
}

func (_c *MockValueDriver_Call_Call) Run(run func(m string, args ...interface{})) *MockValueDriver_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockValueDriver_Call_Call) Return(_a0 js.Value) *MockValueDriver_Call_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Call_Call) RunAndReturn(run func(string, ...interface{}) js.Value) *MockValueDriver_Call_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: p
func (_m *MockValueDriver) Delete(p string) {
	_m.Called(p)
}

// MockValueDriver_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockValueDriver_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - p string
func (_e *MockValueDriver_Expecter) Delete(p interface{}) *MockValueDriver_Delete_Call {
	return &MockValueDriver_Delete_Call{Call: _e.mock.On("Delete", p)}
}

func (_c *MockValueDriver_Delete_Call) Run(run func(p string)) *MockValueDriver_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockValueDriver_Delete_Call) Return() *MockValueDriver_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockValueDriver_Delete_Call) RunAndReturn(run func(string)) *MockValueDriver_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Equal provides a mock function with given fields: w
func (_m *MockValueDriver) Equal(w js.Value) bool {
	ret := _m.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for Equal")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(js.Value) bool); ok {
		r0 = rf(w)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_Equal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Equal'
type MockValueDriver_Equal_Call struct {
	*mock.Call
}

// Equal is a helper method to define mock.On call
//   - w js.Value
func (_e *MockValueDriver_Expecter) Equal(w interface{}) *MockValueDriver_Equal_Call {
	return &MockValueDriver_Equal_Call{Call: _e.mock.On("Equal", w)}
}

func (_c *MockValueDriver_Equal_Call) Run(run func(w js.Value)) *MockValueDriver_Equal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(js.Value))
	})
	return _c
}

func (_c *MockValueDriver_Equal_Call) Return(_a0 bool) *MockValueDriver_Equal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Equal_Call) RunAndReturn(run func(js.Value) bool) *MockValueDriver_Equal_Call {
	_c.Call.Return(run)
	return _c
}

// Float provides a mock function with given fields:
func (_m *MockValueDriver) Float() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Float")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockValueDriver_Float_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Float'
type MockValueDriver_Float_Call struct {
	*mock.Call
}

// Float is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) Float() *MockValueDriver_Float_Call {
	return &MockValueDriver_Float_Call{Call: _e.mock.On("Float")}
}

func (_c *MockValueDriver_Float_Call) Run(run func()) *MockValueDriver_Float_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_Float_Call) Return(_a0 float64) *MockValueDriver_Float_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Float_Call) RunAndReturn(run func() float64) *MockValueDriver_Float_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: p
func (_m *MockValueDriver) Get(p string) js.Value {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func(string) js.Value); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockValueDriver_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockValueDriver_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - p string
func (_e *MockValueDriver_Expecter) Get(p interface{}) *MockValueDriver_Get_Call {
	return &MockValueDriver_Get_Call{Call: _e.mock.On("Get", p)}
}

func (_c *MockValueDriver_Get_Call) Run(run func(p string)) *MockValueDriver_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockValueDriver_Get_Call) Return(_a0 js.Value) *MockValueDriver_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Get_Call) RunAndReturn(run func(string) js.Value) *MockValueDriver_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with given fields: i
func (_m *MockValueDriver) Index(i int) js.Value {
	ret := _m.Called(i)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func(int) js.Value); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockValueDriver_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockValueDriver_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - i int
func (_e *MockValueDriver_Expecter) Index(i interface{}) *MockValueDriver_Index_Call {
	return &MockValueDriver_Index_Call{Call: _e.mock.On("Index", i)}
}

func (_c *MockValueDriver_Index_Call) Run(run func(i int)) *MockValueDriver_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockValueDriver_Index_Call) Return(_a0 js.Value) *MockValueDriver_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Index_Call) RunAndReturn(run func(int) js.Value) *MockValueDriver_Index_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceOf provides a mock function with given fields: t
func (_m *MockValueDriver) InstanceOf(t js.Value) bool {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for InstanceOf")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(js.Value) bool); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_InstanceOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceOf'
type MockValueDriver_InstanceOf_Call struct {
	*mock.Call
}

// InstanceOf is a helper method to define mock.On call
//   - t js.Value
func (_e *MockValueDriver_Expecter) InstanceOf(t interface{}) *MockValueDriver_InstanceOf_Call {
	return &MockValueDriver_InstanceOf_Call{Call: _e.mock.On("InstanceOf", t)}
}

func (_c *MockValueDriver_InstanceOf_Call) Run(run func(t js.Value)) *MockValueDriver_InstanceOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(js.Value))
	})
	return _c
}

func (_c *MockValueDriver_InstanceOf_Call) Return(_a0 bool) *MockValueDriver_InstanceOf_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_InstanceOf_Call) RunAndReturn(run func(js.Value) bool) *MockValueDriver_InstanceOf_Call {
	_c.Call.Return(run)
	return _c
}

// Int provides a mock function with given fields:
func (_m *MockValueDriver) Int() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Int")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockValueDriver_Int_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Int'
type MockValueDriver_Int_Call struct {
	*mock.Call
}

// Int is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) Int() *MockValueDriver_Int_Call {
	return &MockValueDriver_Int_Call{Call: _e.mock.On("Int")}
}

func (_c *MockValueDriver_Int_Call) Run(run func()) *MockValueDriver_Int_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_Int_Call) Return(_a0 int) *MockValueDriver_Int_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Int_Call) RunAndReturn(run func() int) *MockValueDriver_Int_Call {
	_c.Call.Return(run)
	return _c
}

// Invoke provides a mock function with given fields: args
func (_m *MockValueDriver) Invoke(args ...interface{}) js.Value {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func(...interface{}) js.Value); ok {
		r0 = rf(args...)
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockValueDriver_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type MockValueDriver_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockValueDriver_Expecter) Invoke(args ...interface{}) *MockValueDriver_Invoke_Call {
	return &MockValueDriver_Invoke_Call{Call: _e.mock.On("Invoke",
		append([]interface{}{}, args...)...)}
}

func (_c *MockValueDriver_Invoke_Call) Run(run func(args ...interface{})) *MockValueDriver_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockValueDriver_Invoke_Call) Return(_a0 js.Value) *MockValueDriver_Invoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Invoke_Call) RunAndReturn(run func(...interface{}) js.Value) *MockValueDriver_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// IsNaN provides a mock function with given fields:
func (_m *MockValueDriver) IsNaN() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNaN")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_IsNaN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNaN'
type MockValueDriver_IsNaN_Call struct {
	*mock.Call
}

// IsNaN is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) IsNaN() *MockValueDriver_IsNaN_Call {
	return &MockValueDriver_IsNaN_Call{Call: _e.mock.On("IsNaN")}
}

func (_c *MockValueDriver_IsNaN_Call) Run(run func()) *MockValueDriver_IsNaN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_IsNaN_Call) Return(_a0 bool) *MockValueDriver_IsNaN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_IsNaN_Call) RunAndReturn(run func() bool) *MockValueDriver_IsNaN_Call {
	_c.Call.Return(run)
	return _c
}

// IsNull provides a mock function with given fields:
func (_m *MockValueDriver) IsNull() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNull")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_IsNull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNull'
type MockValueDriver_IsNull_Call struct {
	*mock.Call
}

// IsNull is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) IsNull() *MockValueDriver_IsNull_Call {
	return &MockValueDriver_IsNull_Call{Call: _e.mock.On("IsNull")}
}

func (_c *MockValueDriver_IsNull_Call) Run(run func()) *MockValueDriver_IsNull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_IsNull_Call) Return(_a0 bool) *MockValueDriver_IsNull_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_IsNull_Call) RunAndReturn(run func() bool) *MockValueDriver_IsNull_Call {
	_c.Call.Return(run)
	return _c
}

// IsUndefined provides a mock function with given fields:
func (_m *MockValueDriver) IsUndefined() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsUndefined")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_IsUndefined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUndefined'
type MockValueDriver_IsUndefined_Call struct {
	*mock.Call
}

// IsUndefined is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) IsUndefined() *MockValueDriver_IsUndefined_Call {
	return &MockValueDriver_IsUndefined_Call{Call: _e.mock.On("IsUndefined")}
}

func (_c *MockValueDriver_IsUndefined_Call) Run(run func()) *MockValueDriver_IsUndefined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_IsUndefined_Call) Return(_a0 bool) *MockValueDriver_IsUndefined_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_IsUndefined_Call) RunAndReturn(run func() bool) *MockValueDriver_IsUndefined_Call {
	_c.Call.Return(run)
	return _c
}

// Length provides a mock function with given fields:
func (_m *MockValueDriver) Length() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Length")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockValueDriver_Length_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Length'
type MockValueDriver_Length_Call struct {
	*mock.Call
}

// Length is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) Length() *MockValueDriver_Length_Call {
	return &MockValueDriver_Length_Call{Call: _e.mock.On("Length")}
}

func (_c *MockValueDriver_Length_Call) Run(run func()) *MockValueDriver_Length_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_Length_Call) Return(_a0 int) *MockValueDriver_Length_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Length_Call) RunAndReturn(run func() int) *MockValueDriver_Length_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function with given fields: args
func (_m *MockValueDriver) New(args ...interface{}) js.Value {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func(...interface{}) js.Value); ok {
		r0 = rf(args...)
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockValueDriver_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockValueDriver_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - args ...interface{}
func (_e *MockValueDriver_Expecter) New(args ...interface{}) *MockValueDriver_New_Call {
	return &MockValueDriver_New_Call{Call: _e.mock.On("New",
		append([]interface{}{}, args...)...)}
}

func (_c *MockValueDriver_New_Call) Run(run func(args ...interface{})) *MockValueDriver_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockValueDriver_New_Call) Return(_a0 js.Value) *MockValueDriver_New_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_New_Call) RunAndReturn(run func(...interface{}) js.Value) *MockValueDriver_New_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: p, x
func (_m *MockValueDriver) Set(p string, x interface{}) {
	_m.Called(p, x)
}

// MockValueDriver_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockValueDriver_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - p string
//   - x interface{}
func (_e *MockValueDriver_Expecter) Set(p interface{}, x interface{}) *MockValueDriver_Set_Call {
	return &MockValueDriver_Set_Call{Call: _e.mock.On("Set", p, x)}
}

func (_c *MockValueDriver_Set_Call) Run(run func(p string, x interface{})) *MockValueDriver_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockValueDriver_Set_Call) Return() *MockValueDriver_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockValueDriver_Set_Call) RunAndReturn(run func(string, interface{})) *MockValueDriver_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetIndex provides a mock function with given fields: i, x
func (_m *MockValueDriver) SetIndex(i int, x interface{}) {
	_m.Called(i, x)
}

// MockValueDriver_SetIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIndex'
type MockValueDriver_SetIndex_Call struct {
	*mock.Call
}

// SetIndex is a helper method to define mock.On call
//   - i int
//   - x interface{}
func (_e *MockValueDriver_Expecter) SetIndex(i interface{}, x interface{}) *MockValueDriver_SetIndex_Call {
	return &MockValueDriver_SetIndex_Call{Call: _e.mock.On("SetIndex", i, x)}
}

func (_c *MockValueDriver_SetIndex_Call) Run(run func(i int, x interface{})) *MockValueDriver_SetIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(interface{}))
	})
	return _c
}

func (_c *MockValueDriver_SetIndex_Call) Return() *MockValueDriver_SetIndex_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockValueDriver_SetIndex_Call) RunAndReturn(run func(int, interface{})) *MockValueDriver_SetIndex_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with given fields:
func (_m *MockValueDriver) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockValueDriver_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockValueDriver_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) String() *MockValueDriver_String_Call {
	return &MockValueDriver_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockValueDriver_String_Call) Run(run func()) *MockValueDriver_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_String_Call) Return(_a0 string) *MockValueDriver_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_String_Call) RunAndReturn(run func() string) *MockValueDriver_String_Call {
	_c.Call.Return(run)
	return _c
}

// Truthy provides a mock function with given fields:
func (_m *MockValueDriver) Truthy() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Truthy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockValueDriver_Truthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truthy'
type MockValueDriver_Truthy_Call struct {
	*mock.Call
}

// Truthy is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) Truthy() *MockValueDriver_Truthy_Call {
	return &MockValueDriver_Truthy_Call{Call: _e.mock.On("Truthy")}
}

func (_c *MockValueDriver_Truthy_Call) Run(run func()) *MockValueDriver_Truthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_Truthy_Call) Return(_a0 bool) *MockValueDriver_Truthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Truthy_Call) RunAndReturn(run func() bool) *MockValueDriver_Truthy_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with given fields:
func (_m *MockValueDriver) Type() js.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 js.Type
	if rf, ok := ret.Get(0).(func() js.Type); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(js.Type)
	}

	return r0
}

// MockValueDriver_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockValueDriver_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockValueDriver_Expecter) Type() *MockValueDriver_Type_Call {
	return &MockValueDriver_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockValueDriver_Type_Call) Run(run func()) *MockValueDriver_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueDriver_Type_Call) Return(_a0 js.Type) *MockValueDriver_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValueDriver_Type_Call) RunAndReturn(run func() js.Type) *MockValueDriver_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValueDriver creates a new instance of MockValueDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueDriver {
	mock := &MockValueDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
