// Code generated by mockery v2.43.0. DO NOT EDIT.

package js

import (
	js "github.com/macabot/hypp/js"
	mock "github.com/stretchr/testify/mock"
)

// MockFuncDriver is an autogenerated mock type for the FuncDriver type
type MockFuncDriver struct {
	mock.Mock
}

type MockFuncDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFuncDriver) EXPECT() *MockFuncDriver_Expecter {
	return &MockFuncDriver_Expecter{mock: &_m.Mock}
}

// Release provides a mock function with given fields:
func (_m *MockFuncDriver) Release() {
	_m.Called()
}

// MockFuncDriver_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockFuncDriver_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *MockFuncDriver_Expecter) Release() *MockFuncDriver_Release_Call {
	return &MockFuncDriver_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *MockFuncDriver_Release_Call) Run(run func()) *MockFuncDriver_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFuncDriver_Release_Call) Return() *MockFuncDriver_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFuncDriver_Release_Call) RunAndReturn(run func()) *MockFuncDriver_Release_Call {
	_c.Call.Return(run)
	return _c
}

// ValueDriver provides a mock function with given fields:
func (_m *MockFuncDriver) ValueDriver() js.ValueDriver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValueDriver")
	}

	var r0 js.ValueDriver
	if rf, ok := ret.Get(0).(func() js.ValueDriver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(js.ValueDriver)
		}
	}

	return r0
}

// MockFuncDriver_ValueDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValueDriver'
type MockFuncDriver_ValueDriver_Call struct {
	*mock.Call
}

// ValueDriver is a helper method to define mock.On call
func (_e *MockFuncDriver_Expecter) ValueDriver() *MockFuncDriver_ValueDriver_Call {
	return &MockFuncDriver_ValueDriver_Call{Call: _e.mock.On("ValueDriver")}
}

func (_c *MockFuncDriver_ValueDriver_Call) Run(run func()) *MockFuncDriver_ValueDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFuncDriver_ValueDriver_Call) Return(_a0 js.ValueDriver) *MockFuncDriver_ValueDriver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFuncDriver_ValueDriver_Call) RunAndReturn(run func() js.ValueDriver) *MockFuncDriver_ValueDriver_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFuncDriver creates a new instance of MockFuncDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFuncDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFuncDriver {
	mock := &MockFuncDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
