// Code generated by mockery v2.43.0. DO NOT EDIT.

package js

import (
	js "github.com/macabot/hypp/js"
	mock "github.com/stretchr/testify/mock"
)

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// CopyBytesToGo provides a mock function with given fields: dst, src
func (_m *MockDriver) CopyBytesToGo(dst []byte, src js.Value) int {
	ret := _m.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for CopyBytesToGo")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte, js.Value) int); ok {
		r0 = rf(dst, src)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockDriver_CopyBytesToGo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyBytesToGo'
type MockDriver_CopyBytesToGo_Call struct {
	*mock.Call
}

// CopyBytesToGo is a helper method to define mock.On call
//   - dst []byte
//   - src js.Value
func (_e *MockDriver_Expecter) CopyBytesToGo(dst interface{}, src interface{}) *MockDriver_CopyBytesToGo_Call {
	return &MockDriver_CopyBytesToGo_Call{Call: _e.mock.On("CopyBytesToGo", dst, src)}
}

func (_c *MockDriver_CopyBytesToGo_Call) Run(run func(dst []byte, src js.Value)) *MockDriver_CopyBytesToGo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(js.Value))
	})
	return _c
}

func (_c *MockDriver_CopyBytesToGo_Call) Return(_a0 int) *MockDriver_CopyBytesToGo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_CopyBytesToGo_Call) RunAndReturn(run func([]byte, js.Value) int) *MockDriver_CopyBytesToGo_Call {
	_c.Call.Return(run)
	return _c
}

// CopyBytesToJS provides a mock function with given fields: dst, src
func (_m *MockDriver) CopyBytesToJS(dst js.Value, src []byte) int {
	ret := _m.Called(dst, src)

	if len(ret) == 0 {
		panic("no return value specified for CopyBytesToJS")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(js.Value, []byte) int); ok {
		r0 = rf(dst, src)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockDriver_CopyBytesToJS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyBytesToJS'
type MockDriver_CopyBytesToJS_Call struct {
	*mock.Call
}

// CopyBytesToJS is a helper method to define mock.On call
//   - dst js.Value
//   - src []byte
func (_e *MockDriver_Expecter) CopyBytesToJS(dst interface{}, src interface{}) *MockDriver_CopyBytesToJS_Call {
	return &MockDriver_CopyBytesToJS_Call{Call: _e.mock.On("CopyBytesToJS", dst, src)}
}

func (_c *MockDriver_CopyBytesToJS_Call) Run(run func(dst js.Value, src []byte)) *MockDriver_CopyBytesToJS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(js.Value), args[1].([]byte))
	})
	return _c
}

func (_c *MockDriver_CopyBytesToJS_Call) Return(_a0 int) *MockDriver_CopyBytesToJS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_CopyBytesToJS_Call) RunAndReturn(run func(js.Value, []byte) int) *MockDriver_CopyBytesToJS_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultFuncDriver provides a mock function with given fields:
func (_m *MockDriver) DefaultFuncDriver() js.FuncDriver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultFuncDriver")
	}

	var r0 js.FuncDriver
	if rf, ok := ret.Get(0).(func() js.FuncDriver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(js.FuncDriver)
		}
	}

	return r0
}

// MockDriver_DefaultFuncDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultFuncDriver'
type MockDriver_DefaultFuncDriver_Call struct {
	*mock.Call
}

// DefaultFuncDriver is a helper method to define mock.On call
func (_e *MockDriver_Expecter) DefaultFuncDriver() *MockDriver_DefaultFuncDriver_Call {
	return &MockDriver_DefaultFuncDriver_Call{Call: _e.mock.On("DefaultFuncDriver")}
}

func (_c *MockDriver_DefaultFuncDriver_Call) Run(run func()) *MockDriver_DefaultFuncDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_DefaultFuncDriver_Call) Return(_a0 js.FuncDriver) *MockDriver_DefaultFuncDriver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_DefaultFuncDriver_Call) RunAndReturn(run func() js.FuncDriver) *MockDriver_DefaultFuncDriver_Call {
	_c.Call.Return(run)
	return _c
}

// DefaultValueDriver provides a mock function with given fields:
func (_m *MockDriver) DefaultValueDriver() js.ValueDriver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DefaultValueDriver")
	}

	var r0 js.ValueDriver
	if rf, ok := ret.Get(0).(func() js.ValueDriver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(js.ValueDriver)
		}
	}

	return r0
}

// MockDriver_DefaultValueDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefaultValueDriver'
type MockDriver_DefaultValueDriver_Call struct {
	*mock.Call
}

// DefaultValueDriver is a helper method to define mock.On call
func (_e *MockDriver_Expecter) DefaultValueDriver() *MockDriver_DefaultValueDriver_Call {
	return &MockDriver_DefaultValueDriver_Call{Call: _e.mock.On("DefaultValueDriver")}
}

func (_c *MockDriver_DefaultValueDriver_Call) Run(run func()) *MockDriver_DefaultValueDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_DefaultValueDriver_Call) Return(_a0 js.ValueDriver) *MockDriver_DefaultValueDriver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_DefaultValueDriver_Call) RunAndReturn(run func() js.ValueDriver) *MockDriver_DefaultValueDriver_Call {
	_c.Call.Return(run)
	return _c
}

// FuncOf provides a mock function with given fields: fn
func (_m *MockDriver) FuncOf(fn func(js.Value, []js.Value) interface{}) js.Func {
	ret := _m.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for FuncOf")
	}

	var r0 js.Func
	if rf, ok := ret.Get(0).(func(func(js.Value, []js.Value) interface{}) js.Func); ok {
		r0 = rf(fn)
	} else {
		r0 = ret.Get(0).(js.Func)
	}

	return r0
}

// MockDriver_FuncOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FuncOf'
type MockDriver_FuncOf_Call struct {
	*mock.Call
}

// FuncOf is a helper method to define mock.On call
//   - fn func(js.Value , []js.Value) interface{}
func (_e *MockDriver_Expecter) FuncOf(fn interface{}) *MockDriver_FuncOf_Call {
	return &MockDriver_FuncOf_Call{Call: _e.mock.On("FuncOf", fn)}
}

func (_c *MockDriver_FuncOf_Call) Run(run func(fn func(js.Value, []js.Value) interface{})) *MockDriver_FuncOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(js.Value, []js.Value) interface{}))
	})
	return _c
}

func (_c *MockDriver_FuncOf_Call) Return(_a0 js.Func) *MockDriver_FuncOf_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_FuncOf_Call) RunAndReturn(run func(func(js.Value, []js.Value) interface{}) js.Func) *MockDriver_FuncOf_Call {
	_c.Call.Return(run)
	return _c
}

// Global provides a mock function with given fields:
func (_m *MockDriver) Global() js.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Global")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func() js.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockDriver_Global_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Global'
type MockDriver_Global_Call struct {
	*mock.Call
}

// Global is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Global() *MockDriver_Global_Call {
	return &MockDriver_Global_Call{Call: _e.mock.On("Global")}
}

func (_c *MockDriver_Global_Call) Run(run func()) *MockDriver_Global_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Global_Call) Return(_a0 js.Value) *MockDriver_Global_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_Global_Call) RunAndReturn(run func() js.Value) *MockDriver_Global_Call {
	_c.Call.Return(run)
	return _c
}

// Null provides a mock function with given fields:
func (_m *MockDriver) Null() js.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Null")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func() js.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockDriver_Null_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Null'
type MockDriver_Null_Call struct {
	*mock.Call
}

// Null is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Null() *MockDriver_Null_Call {
	return &MockDriver_Null_Call{Call: _e.mock.On("Null")}
}

func (_c *MockDriver_Null_Call) Run(run func()) *MockDriver_Null_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Null_Call) Return(_a0 js.Value) *MockDriver_Null_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_Null_Call) RunAndReturn(run func() js.Value) *MockDriver_Null_Call {
	_c.Call.Return(run)
	return _c
}

// Undefined provides a mock function with given fields:
func (_m *MockDriver) Undefined() js.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Undefined")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func() js.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockDriver_Undefined_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Undefined'
type MockDriver_Undefined_Call struct {
	*mock.Call
}

// Undefined is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Undefined() *MockDriver_Undefined_Call {
	return &MockDriver_Undefined_Call{Call: _e.mock.On("Undefined")}
}

func (_c *MockDriver_Undefined_Call) Run(run func()) *MockDriver_Undefined_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Undefined_Call) Return(_a0 js.Value) *MockDriver_Undefined_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_Undefined_Call) RunAndReturn(run func() js.Value) *MockDriver_Undefined_Call {
	_c.Call.Return(run)
	return _c
}

// ValueOf provides a mock function with given fields: x
func (_m *MockDriver) ValueOf(x interface{}) js.Value {
	ret := _m.Called(x)

	if len(ret) == 0 {
		panic("no return value specified for ValueOf")
	}

	var r0 js.Value
	if rf, ok := ret.Get(0).(func(interface{}) js.Value); ok {
		r0 = rf(x)
	} else {
		r0 = ret.Get(0).(js.Value)
	}

	return r0
}

// MockDriver_ValueOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValueOf'
type MockDriver_ValueOf_Call struct {
	*mock.Call
}

// ValueOf is a helper method to define mock.On call
//   - x interface{}
func (_e *MockDriver_Expecter) ValueOf(x interface{}) *MockDriver_ValueOf_Call {
	return &MockDriver_ValueOf_Call{Call: _e.mock.On("ValueOf", x)}
}

func (_c *MockDriver_ValueOf_Call) Run(run func(x interface{})) *MockDriver_ValueOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockDriver_ValueOf_Call) Return(_a0 js.Value) *MockDriver_ValueOf_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDriver_ValueOf_Call) RunAndReturn(run func(interface{}) js.Value) *MockDriver_ValueOf_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
