#!/bin/bash

set -e

# When committing a Go file, run the tests.
# Tests are run in a temporary directory containing only the stages changes.
# See http://newartisans.com/2009/02/building-a-better-pre-commit-hook-for-git/
if git diff --cached --name-only | grep -qE '\.go$|^go\.(mod|sum)$'; then
	tmp_dir=$(mktemp --directory)
	echo "tmp_dir: ${tmp_dir}" >&2

	git checkout-index --prefix="${tmp_dir}/" -af

	(
		cd "$tmp_dir"
		readarray -t packages < <(go list ./... 2>/dev/null | grep -vE 'cmd|jsd')
		go test "${packages[@]}"
	)

	rm -rf "$tmp_dir"
fi
